import 'package:get/get.dart';

class ChangeLanguage extends Translations {
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'Choose Your Language': 'Choose The Language',
          "Mobile": "Mobile Number",
          "Password": "Password",
          "Confirm Password": "Confirm Password",
          "Current Password": "Current Password",
          "New Password": "New Password",
          "New Confirm Password": "New Confirm Password",
          "Forget Password": "Forgot Password?",
          'Sign in': 'Sign In',
          'New member': 'New User',
          "Next": "Next",
          "Enter Code": "Enter The Confirmation Code",
          "Change Password": "Change Password",
          "Confirm": "Confirm",
          "Full Name": "Full Name",
          "Email": "Email",
          "Sign Up": "Create Account",
          "Account": "Account",
          "Do You Hava Account": "Do you have any account?",
          "My Account": "Account",
          "Profile": "Profile",
          "Update Profile": "Update Profile",
          "Cart": "Cart",
          "Favorite": "Favorite",
          "Products": "Products",
          "Product": "Product",
          "Home": "Home",
          "Orders History": "Orders History",
          "Contact US": "Contact US",
          "Logout": "Log out",
          "Account Info": "Account Info",
          "Addresses": "Addresses",
          "History": "History",
          "Notifications": "Notifications",
          "Language": "Language",
          "English": "English",
          "Arabic": "Arabic",
          "Request": "Request",
          "Photo": "Photo",
          "File": "File",
          "Message": "Message",
          "Typing...":"Typing...",
          "No Messages Here Yet": "No Messages Here Yet",
          "Type message": "Type Message",
          "Search": "Search for anything",
          "Categories": "Categories",
          "Brands": "Brands",
          "See All": "See All",
          "Category Name": "Category Name",
          "Item Name": "Item Name",
          "Login Successfully": "Login Successfully",
          "Register Successfully": "Register Successfully",
          "Updated Successfully": "Updated Successfully",
          "Log out Successfully": "Log out Successfully",
          "Change Password Successfully": "Change Password Successfully",
          "The given data was invalid": "The Given Data Was Invalid",
          "Please Enter Phone": "Please Enter Phone",
          "Please Enter Password": "Please Enter Password",
          "Please Enter Phone And Password": "Please Enter Phone And Password",
          "Password length not less than 8": "Password length not less than 8",
          "Please Enter Name": "Please Enter Name",
          "password mis match  confirm passwrod":
              "Password Doesn\'t Match  Confirm Passwrod",
          "Cant\'t be empty": "Cant\'t Be Empty",
          "Too short": "Too Short",
          "Please enter valid email": "Please Enter Valid Email",
          "phone length equal 9": "Phone Length Equal 9",
          "Address": "Address",
          "Products Count": "Products Count",
          "Order Status": "Order Status",
          "Total": "Total",
          "Price": "Price",
          "Discount": "Discount",
          "Count": "Count of products",
          "City": "City",
          "Order Number": "Order Number",
          "َQty": "Quantity",
          "Specifications": "Specifications",
          "No Specifications": "No Specifications",
          "Wallet": "Wallet",
          "Weight": "Weight",
          "SDG": "SDG",
          "Order Detials": "Order Detials",
          "Is Replaced": "Is Replaced",
          "Total After Replacement": "Total After Replacement",
          "The Cart Is Empty": "The Cart Is Empty",
          "There No Fav": "There Are No Favorites",
          "There No Products": "There Are No Products",
          "There No Colors": "There Are No Colors",
          "There No Sizes": "There Are No Sizes",
          "There No Categories": "There Are No Categories",
          "There No Brands": "There Are No Brands",
          "There No Orders": "There Are No Orders",
          "welcome to yarazon choose department":
              "Welcome To Yarazon Choose Department",
          "Choose Dept": "Choose Department",
          "Start Chat": "Start Chat",
          "Chat": "Chat",
          "Say hello": "Say Hello",
          "Downloaded Successfully": "Downloaded Successfully",
          "Sended Successfully": "Sent Successfully",
          "Add To Cart": "Add To Cart",
          "Remove From Cart": "Remove From Cart",
          "Total(3) Items": "Total(3) Items",
          "Item Specs": "Item Specs",
          "Buy Now": "Buy Now",
          "Color": "Color",
          "Size": "Size",
          "Filter": "Filter",
          "Available Colors": "Available Colors",
          "Available Sizes": "Available Sizes",
          "Apply": "Apply",
          "Discard": "Discard",
          "Last Offers": "Last Offers",
          "Description": "Description",
          "Colors": "Colors",
          "Sizes": "Sizes",
          "Wirte Review": "Write Review",
          "Edit Review": "Edit Review",
          "Users Reviews": "Users Reviews",
          "Rate it!": "'Rate it!",
          "Same Products": "Same Products",
          "Most Visited Products": "Most Visited Products",
          "Latest products": "Latest Products",
          "Added item to cart!": "Added Item To Cart!",
          "Added item to fav!": "Added Item To Favorite!",
          "removed item to fav!": "Removed Item From Favorite!",
          "removed item to cart!": "Removed Item From Cart!",
          "UNDO": "Undo",
          "Sort": "Sort By",
          "Price:": "Price:",
          "lowest to high": "Lowest to high",
          "highest to low": "Highest to low",
          "Search Support":"Search",
          "Clear": "Clear",
          "No Reviews": "No Reviews",
          "Rated Successfully": "Rated Successfully",
          "You have fetched all of the products":
              "You have fetched all of the products",
          "You should login": "You should login",
          "Search Results": "Search Results ...",
          "Cancel": "Cancel",
          "Are you sure to empty the cart": "Are you sure to empty the cart?",
          "Cart empty": "Cart empty",
          "Rated deleted successfully": "Rated deleted successfully",
          "Rated edited successfully": "Rated edited successfully",
          "Back": "Back",
          "Password changed successfully": "Password Changed Successfully",
          "verify code was sent": "Verify Code Was Sent",
          "verify code is valid": "verify code is valid",
          "Product Image": "Product Image",
          "Product Name": "Product Name",
          "Product Descripttion": "Product Descripttion",
          "You can't add product twice": "You Can't Add Product Twice",
          "welcome to yarazon":"Welcome to yarazon",
          "Write your address":"Write your address",
          "Find us on social media :":"Find us on social media :"
        },
        'ar_SD': {
          'Choose Your Language': 'اختر اللغة',
          "Mobile": "رقم الهاتف",
          "Password": "كلمة المرور",
          "Confirm Password": "تأكيد كلمة المرور",
          "Current Password": "كلمة المرور الحالية",
          "New Password": "كلمة المرور الجديدة",
          "New Confirm Password": "تأكيد كلمة المرور الجديدة",
          "Forget Password": "هل نسيت كلمة المرور؟",
          'Sign in': 'تسجيل الدخول',
          "New member": "مستخدم جديد؟",
          "Next": "التالي",
          "Enter Code": "ادخل رمز التأكيد",
          "Change Password": "تغيير كلمة المرور",
          "Confirm": "تأكيد",
          "Full Name": "الاسم كاملاً",
          "Email": "البريد الإلكتروني",
          "Sign Up": " إنشاء حساب",
          "Account": "حساب",
          "Do You Hava Account": "هل تمتلك أي حساب؟",
          "My Account": "حسابي",
          "Profile": "الملف الشخصي",
          "Update Profile": "تحديث البروفايل",
          "Cart": "السلة",
          "Favorite": "المفضلة",
          "Product": "المنتج",
          "Home": "الرئيسية",
          "Mohammed Ali": "محمد علي",
          "Orders History": "سجل الطلبات",
          "Contact US": "تواصل معنا",
          "Logout": "تسجيل خروج",
          "Account Info": "معلومات الحساب",
          "Addresses": "العناوين",
          "History": "السجل",
          "Notifications": "الإشعارات",
          "Language": "اللغة",
          "English": "إنجليزي",
          "Arabic": "عربية",
          "Request": "اطلب",
          "Photo": "صورة",
          "File": "ملف",
          "Message": "الرسالة",
          "Typing...":"يكتب...",
          "Search Support":"بحث",
          "No Messages Here Yet": "لا توجد رسائل هنا حتى الآن",
          "Type message": "اكتب الرسالة",
          "Search": "ابحث عن أي شيء",
          "Categories": "التصنيفات",
          "Brands": "العلامات التجارية",
          "See All": "عرض الكل",
          "Category Name": "اسم القسم",
          "Item Name": "اسم المنتج",
          "Login Successfully": "تم تسجيل الدخول بنجاح",
          "Register Successfully": "تم التسجيل بنجاح",
          "Updated Successfully": "تم التحديث بنجاح",
          "Log out Successfully": "تم تسجيل الخروج بنجاح",
          "Change Password Successfully": "تم تغيير كلمة المرور بنجاح",
          "The given data was invalid": "البيانات المدخلة غير صحيحة",
          "Please Enter Phone": "الرجاء إدخال رقم الهاتف",
          "Please Enter Password": "الرجاء إدخال كلمة المرور",
          "Please Enter Phone And Password":
              "الرجاء إدخال رقم الهاتف وكلمة المرور",
          "Password length not less than 8":
              "طول كلمة المرور لا يقل عن ثمانية حروف ",
          "Please Enter Name": "الرجاء إدخال الإسم",
          "password mis match  confirm passwrod": "كلمة المرور غير متطابقتين",
          "Cant\'t be empty": "لا يمكن ترك الحقل فارغ",
          "Too short": "قصير جداً",
          "Please enter valid email": "البريد الإلكتروني المدخل غير صحيح",
          "phone length equal 9": "طول رقم الهاتف يساوي تسعة أرقام",
          "Address": "العنوان",
          "Products": "المنتجات",
          "Products Count": "عدد المنتجات",
          "Order Status": "حالة الطلب",
          "Order Detials": "تفاصيل الطلب",
          "Total": "السعر النهائي",
          "Price": "السعر",
          "Discount": "الخصم",
          "Count": "عدد المنتجات",
          "City": "المدينة",
          "Order Number": "رقم الطلب",
          "َQty": "عدد القطع",
          "View Product": "عرض المنتج",
          "Specifications": "المواصفات",
          "No Specifications": "لا توجد مواصفات",
          "Wallet": "محفظتي",
          "Weight": "الوزن",
          "SDG": "جنية",
          "Is Replaced": "تم استبداله",
          "Total After Replacement": "السعر بعد الاستبدال",
          "The Cart Is Empty": "السلة فارغة",
          "There No Fav": "لا توجد مفضلة",
          "There No Products": "لا توجد منتجات",
          "There No Colors": "لا توجد ألوان",
          "There No Sizes": "لا توجد مقاسات",
          "There No Categories": "لا توجد تصنيفات",
          "There No Brands": "لا توجد علامات تجارية",
          "There No Orders": "لا توجد طلبات",
          "welcome to yarazon choose department":
              "مرحباً بكم في يارازون اختر القسم",
          "Choose Dept": "اختر القسم",
          "Start Chat": "بدء المحادثة",
          "Chat": "محادثة",
          "Say hello": "قل مرحبًا",
          "Downloaded Successfully": "تم التنزيل بنجاح",
          "Sended Successfully": "تم الارسال بنجاح",
          "Add To Cart": "إضافة إلى السلة",
          "Remove From Cart": "حذف من السلة",
          "Total(3) Items": "مجموع 3 منتجات",
          "Item Specs": "مواصفات المنتج",
          "Buy Now": "اشتري الآن",
          "Color": "اللون",
          "Size": "الحجم",
          "Filter": "فلترة ",
          "Price range": "نطاق السعر",
          "Available Colors": "الألوان المتاحة",
          "Available Sizes": "المقاسات المتاحة",
          "Apply": "تأكيد",
          "Discard": "تجاهل",
          "Last Offers": "آخر العروض",
          "Description": "الوصف",
          "Colors": "الألوان",
          "Sizes": "المقاسات",
          "Wirte Review": "أكتب تقييم",
          "Edit Review": "تعديل تقييم",
          "Users Reviews": "مراجعات المستخدمين",
          "Rate it!": "قيمه!",
          "Same Products": "منتجات مشابهة",
          "Most Visited Products": "المنتجات الأكثر زيارة",
          "Latest products": "المنتجات المضافة حديثاً",
          "Added item to cart!": "تم اضافة المنتج إلى السلة",
          "Added item to fav!": "تم اضافة المنتج إلى المفضلة",
          "removed item to fav!": "تم حذف المنتج من المفضلة",
          "removed item to cart!": "تم حذف المنتج من السلة",
          "UNDO": "تراجع",
          "Sort": "ترتيب حسب",
          "Price:": "السعر:",
          "lowest to high": "من الأقل إلى الأعلى",
          "highest to low": "من الأعلى إلى الأقل",
          "Clear": "تراجع",
          "No Reviews": "لا توجد تقييمات",
          "Rated Successfully": "تم التقييم بنجاح",
          "You have fetched all of the products": "تم عرض كل المنتجات",
          "You should login": "يجب تسجيل الدخول",
          "Search Results": "نتائج البحث ...",
          "Cancel": "الغاء",
          "Are you sure to empty the cart":
              "هل أنت متأكد من حذف منتجات سلة الشراء؟",
          "Cart empty": "سلة الشراء فارغة",
          "Rated deleted successfully": "تم حذف التقييم بنجاح",
          "Rated edited successfully": "تم تعديل التقييم بنجاح",
          "Back": "رجوع",
          "Password changed successfully": "تم تغيير كلمة المرور بنجاح",
          "verify code was sent": "تم إرسال رمز التحقق",
          "verify code is valid": "رمز التحقق صالح",
          "Product Image": "صورة المنتج",
          "Product Name": "اسم المنتج",
          "Product Descripttion": "وصف المنتج",
          "You can't add product twice": "لا يمكنك إضافة المنتج مرتين",
          "welcome to yarazon":"مرحبا بك في يارازون",
          "Write your address":"اكتب عنوانك",
          "Find us on social media :":"مواقع التواصل الإجتماعي"
        }
      };
}
