name: yarazon
description: ecommerce app.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter:
  flutter_launcher_icons: ^0.9.2
  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  get: ^4.6.5
  image_picker: ^0.8.5+3
  http: ^0.13.4
  url_launcher: ^6.1.2
  mime: ^1.0.2
  file_picker: ^4.6.0
  open_file: ^3.2.1
  share_plus: ^4.0.10
  logger: ^1.1.0
  fluttertoast: ^8.0.9
  loading_animation_widget: ^1.2.0+1
  cached_network_image: ^3.2.1
  accordion: ^2.4.0
  dio: ^4.0.6
  intl: ^0.17.0
  carousel_slider: ^4.1.1
  cometchat: ^3.0.3
  flutter_svg: ^1.1.0
  flutter_rating_bar: ^4.0.1
  linkwell: ^2.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/imgs/icon.png"
  image_path_android: "assets/imgs/icon.png"
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/icons/
  fonts:
    - family: LBC
      fonts:
        - asset: assets/fonts/Janna.ttf
    - family: lucymar
      fonts:
        - asset: assets/fonts/LucymarSans-Regular.ttf
